
% Example script for training a semantic segmentation object
% (WholeBloodSegmenter).

% Define image parameters
imgSize = [512,688];
% Images are chopped up into random patches to fit onto the GPU.
patchSize = [256,256];

mySeg = WholeBloodSegmenter(patchSize, 'resnet50');

mySeg.setLabelDir('\\PathToLabelMatrices');
mySeg.setInputDir('\\PathToRawData');
mySeg.setOutputDir('\\PathToOutputFolder');

mySeg.partitionData();
mySeg.enableAugmenter(augmenter);
mySeg.enablePatching(patchSize);

augmenter = imageDataAugmenter(...
    'RandXReflection',true,...
    'RandYReflection',true,...
    'RandXScale', [.7, 1.5], ...
    'RandYScale', [.7, 1.5], ...
    'RandXTranslation',[-10 10], ...
    'RandYTranslation',[-10 10]);

opts = trainingOptions('sgdm',...
    'InitialLearnRate',1E-3, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',20,...
    'LearnRateDropFactor',0.5,...
    'ValidationData',mySeg.pximdsVal,...
    'MaxEpochs',200, ...
    'MiniBatchSize',8, ...
    'CheckpointPath', mySeg.tempdir, ...
    'VerboseFrequency',2,...
    'Plots','training-progress',...
    'ValidationPatience', 20, ...
    'ValidationFrequency', 10);

mySeg.setTrainingOptions(opts);
mySeg.trainNet();
mySeg.segmentDatastore('All');
