
% Test script for generating

imgSize = [512,688];
patchSize = [256,256];
fillValue = 180;

mySeg = WholeBloodSegmenter(patchSize, 'resnet50');

mySeg.setLabelDir('\\Flexo\MicroscopyData\Bioengineering\UV Microscopy\Processed data\Malaria imaging\Processed for publication\Matlab RBC Segmentation training\U-net results UVM-2019-05-30-15-45-12');
mySeg.setInputDir('\\Flexo\MicroscopyData\Bioengineering\UV Microscopy\Processed data\Malaria imaging\Processed for publication\Matlab RBC Segmentation training\Copy of UVM-2019-05-30-15-45-12 refocused');
mySeg.setOutputDir('\\Flexo\MicroscopyData\Bioengineering\UV Microscopy\Processed data\Malaria imaging\Processed for publication\Matlab RBC Segmentation training\Output');

mySeg.partitionData();
mySeg.enableAugmenter(augmenter);
mySeg.enablePatching(patchSize);

augmenter = imageDataAugmenter(...
    'RandXReflection',true,...
    'RandYReflection',true,...
    'RandXScale', [.7, 1.5], ...
    'RandYScale', [.7, 1.5], ...
    'RandXTranslation',[-10 10], ...
    'RandYTranslation',[-10 10]);

% mySeg.balanceClassWeights();
%     'Momentum',0.9, ...
%     'L2Regularization',0.0001, ...

opts = trainingOptions('sgdm',...
    'InitialLearnRate',1E-3, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropPeriod',20,...
    'LearnRateDropFactor',0.5,...
    'ValidationData',mySeg.pximdsVal,...
    'MaxEpochs',200, ...
    'MiniBatchSize',8, ...
    'CheckpointPath', mySeg.tempdir, ...
    'VerboseFrequency',2,...
    'Plots','training-progress',...
    'ValidationPatience', 20, ...
    'ValidationFrequency', 10);

mySeg.setTrainingOptions(opts);

mySeg.trainNet();
mySeg.segmentDatastore('All');
